-- CREATE IT_COMPANY DATABASE
CREATE DATABASE IT_COMPANY;

USE IT_COMPANY;

CREATE TABLE EMPLOYEE(
    ID INT NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    DEPT VARCHAR(20) NOT NULL,
    SALARY INT UNSIGNED NOT NULL,
    LOCATION VARCHAR(25) DEFAULT 'INDIA',
    PRIMARY KEY(ID)
);

-- CHECK TABLE INFO
DESCRIBE EMPLOYEE;
INSERT INTO EMPLOYEE 
VALUES(101,'SWARNA','CSE',1000,'HYD');

SELECT * FROM EMPLOYEE;