-- CREATE DATABASE
CREATE DATABASE FRUITS;

-- SELECT DATABASE
 USE FRUITS;

-- CREATE NEW FRUITPRICES TABLE
-- COLUMNS ARE- NAME, COLOR, PRICE
CREATE TABLE FRUITPRICES(
    NAME VARCHAR(30),
    COLOR VARCHAR(20),
    PRICE INT
);

-- CHECK TABLE DISCRIPTION: SYNTAX: DESCRIBE Table_name
DESCRIBE FRUITPRICES;

-- CREATE NEW DATABASE SCHOOL 
CREATE DATABASE SCHOOL;
-- SELECT SCHOOL DATABASE 
USE SCHOOL;
-- CREATE NEW TABLE STUDENT COLUMNS ARE: ID, NAME, AGE
CREATE TABLE IF NOT EXISTS STUDENTS(
ID INT,
NAME VARCHAR(30),
AGE TINYINT
);

-- DESCRIBE STUDENTS TABLE
DESCRIBE STUDENTS;

-- INSERT DATA INTO TABLE
-- DIRECT VALUES 
INSERT INTO STUDENTS
VALUES(1, 'RAVI', 12);


INSERT INTO STUDENTS
VALUES (1, 'RAVI', 12),
        (2, 'RAJU', 10);
        
INSERT INTO STUDENTS
VALUES(1, 'RAVI');
-- FETCH DATA FROM TABLE
SELECT * FROM STUDENTS;

-- INSERT DATA WITH COLUMNS
INSERT INTO STUDENTS(ID, NAME)
VALUES (1, 'RAVI'),
       (2, 'RAJU');
-- FETCH DATA FROM TABLE
SELECT * FROM STUDENTS;

-- ADD NEW COLUMN PERCENTAGE
ALTER TABLE STUDENTS ADD COLUMN PERCENTAGE FLOAT(4,2);

-- DESCRIBE STUDENTS TABLE
DESCRIBE STUDENTS;
-- CHECK TABLE DATA
SELECT * FROM STUDENTS;
-- DELETE AGE COLUMN FROM STUDENTS TABLE
 ALTER TABLE STUDENTS DROP COLUMN AGE;
 
 -- CHANGE THE ID COLUMN NAME AS STDID
 ALTER TABLE STUDENTS RENAME COLUMN ID TO STDID;

DESCRIBE STUDENTS;