USE IT_COMPANY;

SHOW tables;

select * from employee;

-- insert into table
INSERT INTO EMPLOYEE(ID,NAME,DEPT,SALARY,LOCATION)
VALUES (102,"RAVI","SALES",45000,"INDIA");

INSERT INTO EMPLOYEE(ID,NAME,DEPT,SALARY)
VALUES (108,"SREENU","IT",45000);

INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPT)
VALUES (103,"RAJU",45000,"");

INSERT INTO EMPLOYEE(ID,NAME,DEPT,SALARY,LOCATION)
VALUES (104,"GEETHU","IT",0,"INDIA");

INSERT INTO EMPLOYEE(ID,NAME,DEPT,SALARY,LOCATION)
VALUES (105,"PRERANA","IT",0,"INDIA");
DESC EMPLOYEE;

INSERT INTO EMPLOYEE(ID,NAME,DEPT,SALARY,LOCATION)
VALUES (106,"VIVEK",45,50000,"INDIA");

INSERT INTO EMPLOYEE(ID,NAME,DEPT,SALARY,LOCATION)
VALUES (107,"RAHUL","HR",35000,"INDIA");


-- FETCH TABLE DATA
SELECT * FROM EMPLOYEE;

-- INCREASE 2000 FOR ALL EMPLOYEES
UPDATE EMPLOYEE SET SALARY = SALARY + 2000;


-- ADD 3000 FOR 'IT' DEPARTMENT EMPLOYEES
SELECT * FROM EMPLOYEE
WHERE DEPT = 'IT';
UPDATE EMPLOYEE SET SALARY = SALARY + 3000
WHERE DEPT = 'IT';


SET SQL_SAFE_UPDATES = 0;

-- DELETE
SELECT * FROM EMPLOYEE
WHERE DEPT = "";
DELETE FROM EMPLOYEE
WHERE DEPT = "";
SELECT * FROM EMPLOYEE;
