-- CREATING NEW DATABASE
-- SYNTAX: CREATE DATABASE Database_name;

CREATE  DATABASE APPLE;


CREATE DATABASE IF NOT EXISTS FRUITS;


-- DELETE DATABASE 
DROP DATABASE APPLE;

DROP DATABASE IF EXISTS APPLE;